<a href="https://colab.research.google.com/github/ranzkov/Pembelajaran-Mesin/blob/main/Week2Modul1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def norm_data(data):
    """
    Melakukan normalisasi data.

    Parameters:
    data (list): Data yang akan dinormalisasi

    Returns:
    list: Data hasil normalisasi
    """
    data_max = max(data)
    data_min = min(data)
    data_len = len(data)

    for i in range(data_len):
        data[i] = (data[i] - data_min) / (data_max - data_min)

    return data

# Contoh Penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data)  # melakukan normalisasi
print(n_data)


[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Mengatur opsi tampilan numpy
np.set_printoptions(precision=6)  # Membulatkan angka desimal hingga 6 angka di belakang koma
np.set_printoptions(suppress=True)  # Menghilangkan notasi ilmiah (e)

# Membentuk data
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli:')
print(data)

# Mendefinisikan obyek MinMaxScaler
scaler = MinMaxScaler()

# Transformasikan data
scaled = scaler.fit_transform(data)
print('Data Normalisasi:')
print(scaled)


Data Asli:
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi:
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Mengatur opsi tampilan numpy
np.set_printoptions(precision=6)  # Membulatkan angka desimal hingga 6 angka di belakang koma
np.set_printoptions(suppress=True)  # Menghilangkan notasi ilmiah (e)

# Membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input dalam bentuk n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli:')
print(data)

# Mendefinisikan obyek StandardScaler
scaler = StandardScaler()

# Transformasikan data
scaled = scaler.fit_transform(data)
print('Data Standarisasi:')
print(scaled)


Data Asli:
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi:
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Inisiasi obyek OrdinalEncoder
oe = OrdinalEncoder()

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi Ordinal Encoder
transform_oe = oe.fit_transform(data)

# Cetak hasil
print('Data Asli:')
print(data)
print('Data Transformasi Ordinal Encoder:')
print(transform_oe)


Data Asli:
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder:
[[2.]
 [0.]
 [1.]
 [3.]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek OneHotEncoder
ohe = OneHotEncoder()

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi One-Hot Encoding
transform_ohe = ohe.fit_transform(data)

# Cetak data asli dan hasil transformasi
print('Data Asli')
print(data)
print('Data Transformasi One-Hot Encoding')
print(transform_ohe.toarray())


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek OneHotEncoder dengan drop='first'
ohe = OneHotEncoder(drop='first')

# Definisikan data dalam bentuk 2D
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi One-Hot Encoding
transform_ohe = ohe.fit_transform(data)

# Cetak data asli dan hasil transformasi
print('Data Asli')
print(data)
print('Data Transformasi One-Hot Encoding')
print(transform_ohe.toarray())


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [ ]:
# Definisikan corpus
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

print('Corpus:')
for doc in corpus:
    print(doc)


Corpus:
the house had a tiny little mouse
the cat saw the mouse
the mouse ran away from the house
the cat finally ate the mouse
the end of the mouse story


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Inisiasi obyek TfidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)


print(resp)



  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
<bound method _cs_matrix.toarray of <5x12 sparse matrix of type '<class 'numpy.float64'>'
	with 18 stored elements in Compressed Sparse Row format>>


In [ ]:
vect.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

In [ ]:
# Definisikan corpus
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Definisikan corpus (contoh data)
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

# Inisiasi obyek TfidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil TF-IDF
print('Hasil TF-IDF:')
print(resp.toarray())

# Cetak token hasil stopword
print('Hasil Token:')
print(vect.get_feature_names_out())


Hasil TF-IDF:
[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.       0.      ]
 [0.       0.       0.       0.670092 0.       0.       0.       0.319302
  0.       0.       0.670092 0.      ]]
Hasil Token:
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Membaca file corpus.txt
with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

# Menghapus newline karakter dari setiap baris
corpus = [line.strip() for line in corpus]

# Inisiasi obyek TfidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
tfidf_matrix = vect.fit_transform(corpus)

# Cetak hasil
print('Fitur TF-IDF:')
print(vect.get_feature_names_out())  # Menampilkan nama fitur
print('Matriks TF-IDF:')
print(tfidf_matrix.toarray())  # Menampilkan matriks TF-IDF


Fitur TF-IDF:
['ate' 'away' 'cat' 'corpus' 'definisikan' 'end' 'finally' 'house'
 'little' 'mouse' 'ran' 'saw' 'story' 'tiny']
Matriks TF-IDF:
[[0.       0.       0.       0.642328 0.76643  0.       0.       0.
  0.       0.       0.       0.       0.       0.      ]
 [0.       0.       0.       1.       0.       0.       0.       0.
  0.       0.       0.       0.       0.       0.      ]
 [0.       0.       0.       0.       0.       0.       0.       0.482467
  0.575683 0.323114 0.       0.       0.       0.575683]
 [0.       0.       0.59005  0.       0.       0.       0.       0.
  0.       0.395163 0.       0.704051 0.       0.      ]
 [0.       0.575683 0.       0.       0.       0.       0.       0.482467
  0.       0.323114 0.575683 0.       0.       0.      ]
 [0.575683 0.       0.482467 0.       0.       0.       0.575683 0.
  0.       0.323114 0.       0.       0.       0.      ]
 [0.       0.       0.       0.       0.       0.657237 0.       0.
  0.       0.368888 0.     